### PR TITLE
Update and extend Chapbook syntax highlighting.

### PR DESCRIPTION
**Pull request by sgranade**
Updates Chapbook support to version 2 and extends the syntax highlighting.

### CODE REVIEW

**Comment by cyrusfirheir** [comment]
Please define Chapbook-2 as a separate grammar, instead of replacing Chapbook-1.

**Comment by sgranade** [comment]
Sure, I can if you’d prefer. The syntax didn’t change from 1 to 2, and under the hood my re-worked grammar is mainly extending what Chapbook constructs it covers, especially in the vars section. But if you think folks will want to keep the old syntax for version 1 I can restore it.

**Comment by cyrusfirheir** [comment]
That'd be preferable indeed, yeah.

**Comment by sgranade** [comment]
Done!

**Comment by cyrusfirheir** [comment]
Squashed and merged. Thanks!

**Pull request closed without merging**
